[models]
DEFAULT_PROBE_TIMEOUT = 3  # Seconds
DEFAULT_ALLOW_TIMEOUT_OVERRIDE = true
DEFAULT_CPE_LIMIT = 50
DEFAULT_CVE_LIMIT = 3
NUMBER_OF_BYTES_TO_RECEIVE = 1024

[api]
DEFAULT_PORTS = [20, 53, 80, 110, 143, 443, 514, 3389]
